name: 🚀 Запрос функционала [RU]
description: Предложите идею, функцию или усовершенствование
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: Спасибо за предложение идеи. Это помогает делать voice-over-translation лучше.
  - type: textarea
    id: description
    attributes:
      label: Опишите ваше предложение
      description: |
        Пожалуйста, подробно опишите вашу идею.

        При необходимости вы можете прикрепить скриншоты примеров (например, если ваша идея связана с UX/UI)
    validations:
      required: true
