name: 🌍 Запрос поддержки сайта [RU]
title: Добавить поддержку ...
description: Предложите сайт для добавления поддержки
labels:
  - support request

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за предложение сайта. Это помогает делать voice-over-translation лучше.

        Учтите, что мы **не занимаемся** поддержкой сайтов, где доступ к видео предоставляется исключительно на платной основе
  - type: textarea
    id: name
    attributes:
      label: Введите название/адрес сайта
      description: Если возможно, пожалуйста, предоставьте ссылку на видео
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      description: Вы можете предоставить дополнительную информацию здесь
